### ISSUE TITLE
关于test的问题

### ISSUE THREAD

**Issue by JackHe1999** [vision4robotics/DarkLighter#2]
你好，用你提供的预训练模型test之后结果并不理想，可以麻烦你提供一下DarkLighter与其他SOTA增强算法的跟踪结果的txt文件吗

**Comment by Jay-Ye** [comment]
Thank you for your comment.
Please note that we use DiMP50 as the base tracker and only light up the template/search patch when testing DarkLighter.
We refer you to [SCT](https://github.com/vision4robotics/SCT) for the code of this part and also for some better performance obtained by our SCT.
Also, the original results are made available [here](https://github.com/vision4robotics/DarkLighter/tree/master/results).

**Comment by JackHe1999** [comment]
谢谢你的回复，看过了SCT中的代码之后我明白你是怎么处理的了
